import { FormField } from '@/types'

export interface FormTemplate {
  id: string
  name: string
  description: string
  category: string
  icon: string
  fields: Array<Omit<FormField, 'id'> & { name: string }>
}

export const formTemplates: FormTemplate[] = [
  {
    id: 'contact',
    name: 'Contact Form',
    description: 'Simple contact form with name, email, and message',
    category: 'General',
    icon: '📧',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'message',
        label: 'Message',
        type: 'textarea',
        required: true,
        placeholder: 'Your message here...',
      },
    ],
  },
  {
    id: 'newsletter',
    name: 'Newsletter Signup',
    description: 'Collect email addresses for your newsletter',
    category: 'Marketing',
    icon: '📰',
    fields: [
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'your@email.com',
      },
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: false,
        placeholder: 'John',
      },
      {
        name: 'consent',
        label: 'I agree to receive marketing emails',
        type: 'checkbox',
        required: true,
      },
    ],
  },
  {
    id: 'feedback',
    name: 'Feedback Form',
    description: 'Gather user feedback and ratings',
    category: 'General',
    icon: '⭐',
    fields: [
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: false,
        placeholder: 'Your name (optional)',
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        required: false,
        placeholder: 'your@email.com (optional)',
      },
      {
        name: 'rating',
        label: 'How would you rate your experience?',
        type: 'select',
        required: true,
        options: ['Excellent', 'Good', 'Average', 'Poor', 'Very Poor'],
      },
      {
        name: 'feedback',
        label: 'Your Feedback',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us what you think...',
      },
    ],
  },
  {
    id: 'support',
    name: 'Support Ticket',
    description: 'Customer support request form',
    category: 'Support',
    icon: '🎫',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        required: true,
        options: ['Low', 'Medium', 'High', 'Urgent'],
      },
      {
        name: 'subject',
        label: 'Subject',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the issue',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of your issue...',
      },
    ],
  },
  {
    id: 'waitlist',
    name: 'Waitlist Signup',
    description: 'Collect signups for product launches',
    category: 'Marketing',
    icon: '🚀',
    fields: [
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'your@email.com',
      },
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        required: false,
        placeholder: 'Your company (optional)',
      },
      {
        name: 'useCase',
        label: 'What will you use this for?',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us about your use case...',
      },
    ],
  },
  {
    id: 'job-application',
    name: 'Job Application',
    description: 'Accept job applications with resume upload',
    category: 'HR',
    icon: '💼',
    fields: [
      {
        name: 'fullName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'position',
        label: 'Position Applied For',
        type: 'text',
        required: true,
        placeholder: 'e.g., Software Engineer',
      },
      {
        name: 'experience',
        label: 'Years of Experience',
        type: 'select',
        required: true,
        options: ['0-1 years', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
      },
      {
        name: 'coverLetter',
        label: 'Cover Letter',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us why you\'re a great fit...',
      },
    ],
  },
  {
    id: 'event-registration',
    name: 'Event Registration',
    description: 'Register attendees for events',
    category: 'Events',
    icon: '🎉',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: false,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'ticketType',
        label: 'Ticket Type',
        type: 'select',
        required: true,
        options: ['General Admission', 'VIP', 'Student', 'Group'],
      },
      {
        name: 'dietaryRestrictions',
        label: 'Dietary Restrictions',
        type: 'text',
        required: false,
        placeholder: 'Any dietary restrictions?',
      },
    ],
  },
  {
    id: 'survey',
    name: 'Customer Survey',
    description: 'Collect customer opinions and data',
    category: 'Research',
    icon: '📊',
    fields: [
      {
        name: 'email',
        label: 'Email (Optional)',
        type: 'email',
        required: false,
        placeholder: 'your@email.com',
      },
      {
        name: 'satisfaction',
        label: 'Overall Satisfaction',
        type: 'select',
        required: true,
        options: ['Very Satisfied', 'Satisfied', 'Neutral', 'Dissatisfied', 'Very Dissatisfied'],
      },
      {
        name: 'recommend',
        label: 'Would you recommend us to others?',
        type: 'select',
        required: true,
        options: ['Definitely', 'Probably', 'Not Sure', 'Probably Not', 'Definitely Not'],
      },
      {
        name: 'improvements',
        label: 'What can we improve?',
        type: 'textarea',
        required: false,
        placeholder: 'Your suggestions...',
      },
    ],
  },
  {
    id: 'quote-request',
    name: 'Quote Request',
    description: 'Get pricing inquiries from potential customers',
    category: 'Sales',
    icon: '💰',
    fields: [
      {
        name: 'companyName',
        label: 'Company Name',
        type: 'text',
        required: true,
        placeholder: 'Acme Inc.',
      },
      {
        name: 'contactName',
        label: 'Contact Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@acme.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: false,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'projectDetails',
        label: 'Project Details',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about your project...',
      },
      {
        name: 'budget',
        label: 'Budget Range',
        type: 'select',
        required: false,
        options: ['Under $5k', '$5k - $10k', '$10k - $25k', '$25k - $50k', '$50k+'],
      },
    ],
  },
  {
    id: 'bug-report',
    name: 'Bug Report',
    description: 'Track and manage bug reports',
    category: 'Support',
    icon: '🐛',
    fields: [
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'your@email.com',
      },
      {
        name: 'title',
        label: 'Bug Title',
        type: 'text',
        required: true,
        placeholder: 'Brief description of the bug',
      },
      {
        name: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: ['Critical', 'High', 'Medium', 'Low'],
      },
      {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Detailed description of the bug...',
      },
      {
        name: 'stepsToReproduce',
        label: 'Steps to Reproduce',
        type: 'textarea',
        required: true,
        placeholder: '1. Go to...\n2. Click on...\n3. See error',
      },
    ],
  },
  {
    id: 'product-feedback',
    name: 'Product Feedback',
    description: 'Collect detailed product feedback from users',
    category: 'Research',
    icon: '💡',
    fields: [
      {
        name: 'productUsed',
        label: 'Which product did you use?',
        type: 'select',
        required: true,
        options: ['Product A', 'Product B', 'Product C', 'Multiple Products'],
      },
      {
        name: 'usageFrequency',
        label: 'How often do you use our product?',
        type: 'select',
        required: true,
        options: ['Daily', 'Weekly', 'Monthly', 'Rarely', 'First time'],
      },
      {
        name: 'rating',
        label: 'Overall Rating',
        type: 'select',
        required: true,
        options: ['5 - Excellent', '4 - Good', '3 - Average', '2 - Poor', '1 - Very Poor'],
      },
      {
        name: 'favoriteFeature',
        label: 'What\'s your favorite feature?',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us what you love most...',
      },
      {
        name: 'improvements',
        label: 'What would you improve?',
        type: 'textarea',
        required: false,
        placeholder: 'Your suggestions for improvement...',
      },
      {
        name: 'email',
        label: 'Email (for follow-up)',
        type: 'email',
        required: false,
        placeholder: 'your@email.com',
      },
    ],
  },
  {
    id: 'lead-generation',
    name: 'Lead Generation',
    description: 'Capture qualified leads for your business',
    category: 'Marketing',
    icon: '🎯',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
      },
      {
        name: 'email',
        label: 'Business Email',
        type: 'email',
        required: true,
        placeholder: 'john@company.com',
      },
      {
        name: 'company',
        label: 'Company Name',
        type: 'text',
        required: true,
        placeholder: 'Acme Inc.',
      },
      {
        name: 'jobTitle',
        label: 'Job Title',
        type: 'text',
        required: true,
        placeholder: 'Marketing Manager',
      },
      {
        name: 'companySize',
        label: 'Company Size',
        type: 'select',
        required: true,
        options: ['1-10 employees', '11-50 employees', '51-200 employees', '201-1000 employees', '1000+ employees'],
      },
      {
        name: 'interest',
        label: 'What are you interested in?',
        type: 'select',
        required: true,
        options: ['Product Demo', 'Pricing Information', 'Free Trial', 'Partnership', 'Other'],
      },
    ],
  },
  {
    id: 'webinar-registration',
    name: 'Webinar Registration',
    description: 'Register attendees for webinars and online events',
    category: 'Events',
    icon: '🎥',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'company',
        label: 'Company',
        type: 'text',
        required: false,
        placeholder: 'Your company name',
      },
      {
        name: 'jobTitle',
        label: 'Job Title',
        type: 'text',
        required: false,
        placeholder: 'Your role',
      },
      {
        name: 'timezone',
        label: 'Timezone',
        type: 'select',
        required: true,
        options: ['EST (UTC-5)', 'CST (UTC-6)', 'MST (UTC-7)', 'PST (UTC-8)', 'GMT (UTC+0)', 'CET (UTC+1)', 'Other'],
      },
      {
        name: 'questions',
        label: 'Questions for the presenter',
        type: 'textarea',
        required: false,
        placeholder: 'Any questions you\'d like answered during the webinar?',
      },
    ],
  },
  {
    id: 'course-enrollment',
    name: 'Course Enrollment',
    description: 'Enroll students in courses and programs',
    category: 'Education',
    icon: '🎓',
    fields: [
      {
        name: 'studentName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'course',
        label: 'Course Selection',
        type: 'select',
        required: true,
        options: ['Web Development Bootcamp', 'Data Science Course', 'Digital Marketing', 'UI/UX Design', 'Mobile App Development'],
      },
      {
        name: 'experience',
        label: 'Experience Level',
        type: 'select',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced'],
      },
      {
        name: 'goals',
        label: 'Learning Goals',
        type: 'textarea',
        required: false,
        placeholder: 'What do you hope to achieve from this course?',
      },
    ],
  },
  {
    id: 'appointment-booking',
    name: 'Appointment Booking',
    description: 'Schedule appointments and consultations',
    category: 'Business',
    icon: '📅',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'serviceType',
        label: 'Service Type',
        type: 'select',
        required: true,
        options: ['Consultation', 'Follow-up', 'New Client Meeting', 'Support Session', 'Other'],
      },
      {
        name: 'preferredDate',
        label: 'Preferred Date',
        type: 'date',
        required: true,
      },
      {
        name: 'preferredTime',
        label: 'Preferred Time',
        type: 'select',
        required: true,
        options: ['9:00 AM', '10:00 AM', '11:00 AM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM'],
      },
      {
        name: 'notes',
        label: 'Additional Notes',
        type: 'textarea',
        required: false,
        placeholder: 'Any specific topics or concerns you\'d like to discuss?',
      },
    ],
  },
  {
    id: 'volunteer-signup',
    name: 'Volunteer Signup',
    description: 'Register volunteers for events and activities',
    category: 'Non-profit',
    icon: '🤝',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'age',
        label: 'Age Group',
        type: 'select',
        required: true,
        options: ['Under 18', '18-25', '26-35', '36-50', '51-65', 'Over 65'],
      },
      {
        name: 'availability',
        label: 'Availability',
        type: 'select',
        required: true,
        options: ['Weekdays', 'Weekends', 'Evenings', 'Flexible', 'One-time event'],
      },
      {
        name: 'skills',
        label: 'Skills & Interests',
        type: 'textarea',
        required: false,
        placeholder: 'What skills or interests would you like to contribute?',
      },
      {
        name: 'experience',
        label: 'Previous Volunteer Experience',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us about your volunteer experience...',
      },
    ],
  },
  {
    id: 'membership-application',
    name: 'Membership Application',
    description: 'Apply for membership in organizations',
    category: 'Business',
    icon: '🏛️',
    fields: [
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'John',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'membershipType',
        label: 'Membership Type',
        type: 'select',
        required: true,
        options: ['Individual', 'Family', 'Student', 'Corporate', 'Lifetime'],
      },
      {
        name: 'referredBy',
        label: 'Referred By',
        type: 'text',
        required: false,
        placeholder: 'Who referred you to us?',
      },
      {
        name: 'interests',
        label: 'Areas of Interest',
        type: 'textarea',
        required: false,
        placeholder: 'What activities or services are you most interested in?',
      },
    ],
  },
  {
    id: 'contest-entry',
    name: 'Contest Entry',
    description: 'Enter contests and giveaways',
    category: 'Marketing',
    icon: '🏆',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: false,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'age',
        label: 'Age',
        type: 'number',
        required: true,
        placeholder: '18',
      },
      {
        name: 'country',
        label: 'Country',
        type: 'select',
        required: true,
        options: ['United States', 'Canada', 'United Kingdom', 'Australia', 'Germany', 'France', 'Other'],
      },
      {
        name: 'socialMedia',
        label: 'Social Media Handle (Optional)',
        type: 'text',
        required: false,
        placeholder: '@username',
      },
      {
        name: 'terms',
        label: 'I agree to the terms and conditions',
        type: 'checkbox',
        required: true,
      },
    ],
  },
  {
    id: 'restaurant-reservation',
    name: 'Restaurant Reservation',
    description: 'Make table reservations at restaurants',
    category: 'Hospitality',
    icon: '🍽️',
    fields: [
      {
        name: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'date',
        label: 'Reservation Date',
        type: 'date',
        required: true,
      },
      {
        name: 'time',
        label: 'Preferred Time',
        type: 'select',
        required: true,
        options: ['5:00 PM', '5:30 PM', '6:00 PM', '6:30 PM', '7:00 PM', '7:30 PM', '8:00 PM', '8:30 PM', '9:00 PM'],
      },
      {
        name: 'partySize',
        label: 'Party Size',
        type: 'select',
        required: true,
        options: ['1 person', '2 people', '3 people', '4 people', '5 people', '6 people', '7+ people'],
      },
      {
        name: 'specialRequests',
        label: 'Special Requests',
        type: 'textarea',
        required: false,
        placeholder: 'Dietary restrictions, special occasion, seating preferences...',
      },
    ],
  },
  {
    id: 'property-inquiry',
    name: 'Property Inquiry',
    description: 'Inquire about real estate properties',
    category: 'Real Estate',
    icon: '🏠',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'propertyType',
        label: 'Property Type',
        type: 'select',
        required: true,
        options: ['House', 'Apartment', 'Condo', 'Townhouse', 'Commercial', 'Land'],
      },
      {
        name: 'budget',
        label: 'Budget Range',
        type: 'select',
        required: true,
        options: ['Under $200k', '$200k-$400k', '$400k-$600k', '$600k-$800k', '$800k-$1M', 'Over $1M'],
      },
      {
        name: 'location',
        label: 'Preferred Location',
        type: 'text',
        required: true,
        placeholder: 'City, State or ZIP code',
      },
      {
        name: 'timeline',
        label: 'Purchase Timeline',
        type: 'select',
        required: true,
        options: ['Immediately', 'Within 3 months', 'Within 6 months', 'Within 1 year', 'Just browsing'],
      },
      {
        name: 'requirements',
        label: 'Specific Requirements',
        type: 'textarea',
        required: false,
        placeholder: 'Bedrooms, bathrooms, amenities, etc.',
      },
    ],
  },
  {
    id: 'medical-appointment',
    name: 'Medical Appointment',
    description: 'Schedule medical appointments and consultations',
    category: 'Healthcare',
    icon: '🏥',
    fields: [
      {
        name: 'patientName',
        label: 'Patient Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'dateOfBirth',
        label: 'Date of Birth',
        type: 'date',
        required: true,
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'appointmentType',
        label: 'Appointment Type',
        type: 'select',
        required: true,
        options: ['General Consultation', 'Follow-up', 'Specialist Referral', 'Routine Check-up', 'Urgent Care'],
      },
      {
        name: 'preferredDate',
        label: 'Preferred Date',
        type: 'date',
        required: true,
      },
      {
        name: 'symptoms',
        label: 'Symptoms/Reason for Visit',
        type: 'textarea',
        required: false,
        placeholder: 'Please describe your symptoms or reason for the appointment...',
      },
      {
        name: 'insurance',
        label: 'Insurance Provider',
        type: 'text',
        required: false,
        placeholder: 'Your insurance provider',
      },
    ],
  },
  {
    id: 'fitness-assessment',
    name: 'Fitness Assessment',
    description: 'Initial fitness evaluation and goal setting',
    category: 'Health & Fitness',
    icon: '💪',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'age',
        label: 'Age',
        type: 'number',
        required: true,
        placeholder: '30',
      },
      {
        name: 'fitnessLevel',
        label: 'Current Fitness Level',
        type: 'select',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced', 'Athlete'],
      },
      {
        name: 'goals',
        label: 'Fitness Goals',
        type: 'select',
        required: true,
        options: ['Weight Loss', 'Muscle Gain', 'Endurance', 'Strength', 'General Health', 'Sport-specific'],
      },
      {
        name: 'experience',
        label: 'Exercise Experience',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us about your exercise history...',
      },
      {
        name: 'injuries',
        label: 'Previous Injuries',
        type: 'textarea',
        required: false,
        placeholder: 'Any injuries or physical limitations we should know about?',
      },
      {
        name: 'availability',
        label: 'Training Availability',
        type: 'select',
        required: true,
        options: ['2-3 times per week', '3-4 times per week', '4-5 times per week', '5+ times per week'],
      },
    ],
  },
  {
    id: 'vendor-application',
    name: 'Vendor Application',
    description: 'Apply to become a vendor or supplier',
    category: 'Business',
    icon: '🏪',
    fields: [
      {
        name: 'companyName',
        label: 'Company Name',
        type: 'text',
        required: true,
        placeholder: 'Acme Supplies Inc.',
      },
      {
        name: 'contactName',
        label: 'Contact Person',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@acmesupplies.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'website',
        label: 'Company Website',
        type: 'text',
        required: false,
        placeholder: 'https://www.acmesupplies.com',
      },
      {
        name: 'productsServices',
        label: 'Products/Services Offered',
        type: 'textarea',
        required: true,
        placeholder: 'Describe what products or services you offer...',
      },
      {
        name: 'experience',
        label: 'Years in Business',
        type: 'select',
        required: true,
        options: ['Less than 1 year', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
      },
      {
        name: 'references',
        label: 'References',
        type: 'textarea',
        required: false,
        placeholder: 'Please provide 2-3 business references...',
      },
    ],
  },
  {
    id: 'workshop-feedback',
    name: 'Workshop Feedback',
    description: 'Collect feedback from workshop attendees',
    category: 'Education',
    icon: '📝',
    fields: [
      {
        name: 'workshopTitle',
        label: 'Workshop Title',
        type: 'select',
        required: true,
        options: ['Digital Marketing 101', 'Leadership Skills', 'Project Management', 'Data Analytics', 'Other'],
      },
      {
        name: 'attendeeName',
        label: 'Your Name (Optional)',
        type: 'text',
        required: false,
        placeholder: 'John Doe',
      },
      {
        name: 'overallRating',
        label: 'Overall Rating',
        type: 'select',
        required: true,
        options: ['5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor'],
      },
      {
        name: 'contentRating',
        label: 'Content Quality',
        type: 'select',
        required: true,
        options: ['5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor'],
      },
      {
        name: 'instructorRating',
        label: 'Instructor Rating',
        type: 'select',
        required: true,
        options: ['5 - Excellent', '4 - Very Good', '3 - Good', '2 - Fair', '1 - Poor'],
      },
      {
        name: 'mostValuable',
        label: 'Most Valuable Part',
        type: 'textarea',
        required: false,
        placeholder: 'What was the most valuable part of the workshop?',
      },
      {
        name: 'improvements',
        label: 'Suggested Improvements',
        type: 'textarea',
        required: false,
        placeholder: 'How could we improve this workshop?',
      },
      {
        name: 'recommend',
        label: 'Would you recommend this workshop?',
        type: 'select',
        required: true,
        options: ['Definitely', 'Probably', 'Maybe', 'Probably Not', 'Definitely Not'],
      },
    ],
  },
  {
    id: 'pet-adoption',
    name: 'Pet Adoption Application',
    description: 'Apply to adopt pets from shelters',
    category: 'Non-profit',
    icon: '🐕',
    fields: [
      {
        name: 'applicantName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'address',
        label: 'Home Address',
        type: 'textarea',
        required: true,
        placeholder: 'Street address, city, state, ZIP code',
      },
      {
        name: 'housingType',
        label: 'Housing Type',
        type: 'select',
        required: true,
        options: ['House with yard', 'House without yard', 'Apartment', 'Condo', 'Other'],
      },
      {
        name: 'petExperience',
        label: 'Pet Experience',
        type: 'textarea',
        required: true,
        placeholder: 'Tell us about your experience with pets...',
      },
      {
        name: 'petInterest',
        label: 'Interested Pet',
        type: 'text',
        required: false,
        placeholder: 'Specific pet name or type you\'re interested in',
      },
      {
        name: 'familyMembers',
        label: 'Family Members',
        type: 'textarea',
        required: true,
        placeholder: 'List all family members and their ages...',
      },
    ],
  },
  {
    id: 'employee-onboarding',
    name: 'Employee Onboarding',
    description: 'Collect new employee information and documents',
    category: 'HR',
    icon: '👋',
    fields: [
      {
        name: 'employeeName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Personal Email',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: true,
      },
      {
        name: 'position',
        label: 'Position/Role',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer',
      },
      {
        name: 'department',
        label: 'Department',
        type: 'select',
        required: true,
        options: ['Engineering', 'Marketing', 'Sales', 'HR', 'Finance', 'Operations', 'Other'],
      },
      {
        name: 'emergencyContact',
        label: 'Emergency Contact',
        type: 'textarea',
        required: true,
        placeholder: 'Name, relationship, and phone number',
      },
      {
        name: 'tshirtSize',
        label: 'T-Shirt Size',
        type: 'select',
        required: false,
        options: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      },
    ],
  },
  {
    id: 'customer-onboarding',
    name: 'Customer Onboarding',
    description: 'Onboard new customers and collect setup information',
    category: 'Business',
    icon: '🎯',
    fields: [
      {
        name: 'companyName',
        label: 'Company Name',
        type: 'text',
        required: true,
        placeholder: 'Acme Inc.',
      },
      {
        name: 'contactName',
        label: 'Primary Contact',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@acme.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'industry',
        label: 'Industry',
        type: 'select',
        required: true,
        options: ['Technology', 'Healthcare', 'Finance', 'Education', 'Retail', 'Manufacturing', 'Other'],
      },
      {
        name: 'companySize',
        label: 'Company Size',
        type: 'select',
        required: true,
        options: ['1-10 employees', '11-50 employees', '51-200 employees', '201-1000 employees', '1000+ employees'],
      },
      {
        name: 'goals',
        label: 'Primary Goals',
        type: 'textarea',
        required: true,
        placeholder: 'What are your main objectives with our service?',
      },
      {
        name: 'timeline',
        label: 'Implementation Timeline',
        type: 'select',
        required: true,
        options: ['ASAP', 'Within 1 month', 'Within 3 months', 'Within 6 months', 'Flexible'],
      },
    ],
  },
  {
    id: 'product-launch-survey',
    name: 'Product Launch Survey',
    description: 'Gather feedback before launching new products',
    category: 'Research',
    icon: '🚀',
    fields: [
      {
        name: 'email',
        label: 'Email (Optional)',
        type: 'email',
        required: false,
        placeholder: 'your@email.com',
      },
      {
        name: 'currentSolution',
        label: 'What solution do you currently use?',
        type: 'text',
        required: false,
        placeholder: 'Current tool or method',
      },
      {
        name: 'painPoints',
        label: 'What are your biggest pain points?',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the challenges you face...',
      },
      {
        name: 'featureImportance',
        label: 'Most important features (rank top 3)',
        type: 'textarea',
        required: true,
        placeholder: 'List the 3 most important features for you...',
      },
      {
        name: 'pricingExpectation',
        label: 'Expected pricing range',
        type: 'select',
        required: true,
        options: ['Free', 'Under $10/month', '$10-$50/month', '$50-$100/month', '$100+/month'],
      },
      {
        name: 'likelihood',
        label: 'How likely are you to use this product?',
        type: 'select',
        required: true,
        options: ['Very likely', 'Likely', 'Maybe', 'Unlikely', 'Very unlikely'],
      },
    ],
  },
  {
    id: 'training-registration',
    name: 'Training Registration',
    description: 'Register for training sessions and workshops',
    category: 'Education',
    icon: '🎓',
    fields: [
      {
        name: 'participantName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'jobTitle',
        label: 'Job Title',
        type: 'text',
        required: true,
        placeholder: 'Software Engineer',
      },
      {
        name: 'company',
        label: 'Company/Organization',
        type: 'text',
        required: true,
        placeholder: 'Acme Inc.',
      },
      {
        name: 'trainingTopic',
        label: 'Training Topic',
        type: 'select',
        required: true,
        options: ['Leadership Development', 'Technical Skills', 'Communication', 'Project Management', 'Sales Training', 'Other'],
      },
      {
        name: 'experienceLevel',
        label: 'Experience Level',
        type: 'select',
        required: true,
        options: ['Beginner', 'Intermediate', 'Advanced', 'Expert'],
      },
      {
        name: 'expectations',
        label: 'Training Expectations',
        type: 'textarea',
        required: false,
        placeholder: 'What do you hope to learn from this training?',
      },
    ],
  },
  {
    id: 'maintenance-request',
    name: 'Maintenance Request',
    description: 'Submit maintenance and repair requests',
    category: 'Business',
    icon: '🔧',
    fields: [
      {
        name: 'requesterName',
        label: 'Your Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'location',
        label: 'Location/Room',
        type: 'text',
        required: true,
        placeholder: 'Building A, Room 101',
      },
      {
        name: 'issueType',
        label: 'Issue Type',
        type: 'select',
        required: true,
        options: ['Plumbing', 'Electrical', 'HVAC', 'Appliance', 'Structural', 'Cleaning', 'Other'],
      },
      {
        name: 'priority',
        label: 'Priority Level',
        type: 'select',
        required: true,
        options: ['Emergency', 'High', 'Medium', 'Low'],
      },
      {
        name: 'description',
        label: 'Issue Description',
        type: 'textarea',
        required: true,
        placeholder: 'Describe the maintenance issue in detail...',
      },
      {
        name: 'preferredTime',
        label: 'Preferred Service Time',
        type: 'select',
        required: false,
        options: ['Morning (8AM-12PM)', 'Afternoon (12PM-5PM)', 'Evening (5PM-8PM)', 'Anytime'],
      },
    ],
  },
  {
    id: 'scholarship-application',
    name: 'Scholarship Application',
    description: 'Apply for educational scholarships and grants',
    category: 'Education',
    icon: '🎓',
    fields: [
      {
        name: 'studentName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'dateOfBirth',
        label: 'Date of Birth',
        type: 'date',
        required: true,
      },
      {
        name: 'currentSchool',
        label: 'Current School/University',
        type: 'text',
        required: true,
        placeholder: 'University of Example',
      },
      {
        name: 'gpa',
        label: 'Current GPA',
        type: 'text',
        required: true,
        placeholder: '3.8',
      },
      {
        name: 'fieldOfStudy',
        label: 'Field of Study',
        type: 'text',
        required: true,
        placeholder: 'Computer Science',
      },
      {
        name: 'financialNeed',
        label: 'Financial Need Statement',
        type: 'textarea',
        required: true,
        placeholder: 'Explain your financial situation and need for scholarship...',
      },
      {
        name: 'achievements',
        label: 'Academic Achievements',
        type: 'textarea',
        required: true,
        placeholder: 'List your academic achievements, awards, and honors...',
      },
    ],
  },
  {
    id: 'smart-product-inquiry',
    name: 'Smart Product Inquiry',
    description: 'Intelligent form that adapts based on product interest',
    category: 'Sales',
    icon: '🧠',
    fields: [
      {
        name: 'name',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'productInterest',
        label: 'Which product are you interested in?',
        type: 'select',
        required: true,
        options: ['Software License', 'Consulting Services', 'Training Program', 'Custom Development'],
      },
      {
        name: 'softwareType',
        label: 'Software Type',
        type: 'select',
        required: true,
        defaultHidden: true,
        options: ['Basic Plan', 'Professional Plan', 'Enterprise Plan'],
      },
      {
        name: 'teamSize',
        label: 'Team Size',
        type: 'select',
        required: true,
        defaultHidden: true,
        options: ['1-5 people', '6-20 people', '21-100 people', '100+ people'],
      },
      {
        name: 'consultingArea',
        label: 'Consulting Area',
        type: 'select',
        required: true,
        defaultHidden: true,
        options: ['Strategy', 'Implementation', 'Optimization', 'Training'],
      },
      {
        name: 'budget',
        label: 'Budget Range',
        type: 'select',
        required: true,
        options: ['Under $5k', '$5k-$15k', '$15k-$50k', '$50k+'],
      },
      {
        name: 'urgency',
        label: 'Timeline',
        type: 'select',
        required: true,
        options: ['ASAP', 'Within 1 month', 'Within 3 months', 'Just exploring'],
      },
      {
        name: 'priorityHandling',
        label: 'Priority Handling Required',
        type: 'checkbox',
        required: false,
        defaultHidden: true,
      },
      {
        name: 'message',
        label: 'Additional Details',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us more about your requirements...',
      },
    ],
  },
  {
    id: 'smart-event-registration',
    name: 'Smart Event Registration',
    description: 'Dynamic registration form with conditional pricing and options',
    category: 'Events',
    icon: '🎯',
    fields: [
      {
        name: 'attendeeName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'attendeeType',
        label: 'Attendee Type',
        type: 'select',
        required: true,
        options: ['Regular', 'Student', 'VIP', 'Speaker'],
      },
      {
        name: 'studentId',
        label: 'Student ID',
        type: 'text',
        required: true,
        defaultHidden: true,
        placeholder: 'Your student ID number',
      },
      {
        name: 'vipPreferences',
        label: 'VIP Preferences',
        type: 'select',
        required: true,
        defaultHidden: true,
        options: ['Front Row Seating', 'Networking Dinner', 'Private Lounge Access', 'All Inclusive'],
      },
      {
        name: 'presentationTopic',
        label: 'Presentation Topic',
        type: 'text',
        required: true,
        defaultHidden: true,
        placeholder: 'Title of your presentation',
      },
      {
        name: 'ticketPrice',
        label: 'Ticket Price',
        type: 'calculated',
        required: false,
        calculation: 'attendeeType === "Student" ? 25 : attendeeType === "VIP" ? 299 : attendeeType === "Speaker" ? 0 : 99',
      },
      {
        name: 'dietaryRestrictions',
        label: 'Dietary Restrictions',
        type: 'text',
        required: false,
        placeholder: 'Any dietary restrictions or allergies?',
      },
      {
        name: 'emergencyContact',
        label: 'Emergency Contact',
        type: 'text',
        required: false,
        placeholder: 'Name and phone number',
      },
    ],
  },
  {
    id: 'smart-job-application',
    name: 'Smart Job Application',
    description: 'Adaptive job application with role-specific questions',
    category: 'HR',
    icon: '🎯',
    fields: [
      {
        name: 'applicantName',
        label: 'Full Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'email',
        label: 'Email Address',
        type: 'email',
        required: true,
        placeholder: 'john@example.com',
      },
      {
        name: 'phone',
        label: 'Phone Number',
        type: 'text',
        required: true,
        placeholder: '+1 (555) 000-0000',
      },
      {
        name: 'position',
        label: 'Position Applied For',
        type: 'select',
        required: true,
        options: ['Software Engineer', 'Product Manager', 'Designer', 'Sales Representative', 'Marketing Manager'],
      },
      {
        name: 'techStack',
        label: 'Technical Skills',
        type: 'textarea',
        required: true,
        defaultHidden: true,
        placeholder: 'List your programming languages, frameworks, and tools...',
      },
      {
        name: 'designPortfolio',
        label: 'Portfolio URL',
        type: 'text',
        required: true,
        defaultHidden: true,
        placeholder: 'https://your-portfolio.com',
      },
      {
        name: 'salesExperience',
        label: 'Sales Experience (Years)',
        type: 'number',
        required: true,
        defaultHidden: true,
        placeholder: '5',
      },
      {
        name: 'experience',
        label: 'Years of Experience',
        type: 'select',
        required: true,
        options: ['0-1 years', '1-3 years', '3-5 years', '5-10 years', '10+ years'],
      },
      {
        name: 'seniorityQuestions',
        label: 'Leadership Experience',
        type: 'textarea',
        required: true,
        defaultHidden: true,
        placeholder: 'Describe your leadership and mentoring experience...',
      },
      {
        name: 'salary',
        label: 'Expected Salary Range',
        type: 'select',
        required: true,
        options: ['$40k-$60k', '$60k-$80k', '$80k-$100k', '$100k-$120k', '$120k+'],
      },
      {
        name: 'coverLetter',
        label: 'Cover Letter',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us why you\'re perfect for this role...',
      },
    ],
  },
  {
    id: 'smart-demo',
    name: 'Smart Logic Demo',
    description: 'See conditional logic in action with this interactive demo',
    category: 'General',
    icon: '🧠',
    fields: [
      {
        name: 'name',
        label: 'Your Name',
        type: 'text',
        required: true,
        placeholder: 'John Doe',
      },
      {
        name: 'userType',
        label: 'I am a...',
        type: 'select',
        required: true,
        options: ['Student', 'Professional', 'Business Owner', 'Other'],
      },
      {
        name: 'studentId',
        label: 'Student ID',
        type: 'text',
        required: true,
        defaultHidden: true,
        placeholder: 'Your student ID',
      },
      {
        name: 'company',
        label: 'Company Name',
        type: 'text',
        required: true,
        defaultHidden: true,
        placeholder: 'Your company',
      },
      {
        name: 'businessSize',
        label: 'Business Size',
        type: 'select',
        required: true,
        defaultHidden: true,
        options: ['1-10 employees', '11-50 employees', '51-200 employees', '200+ employees'],
      },
      {
        name: 'budget',
        label: 'Monthly Budget',
        type: 'select',
        required: false,
        defaultHidden: true,
        options: ['Under $1,000', '$1,000-$5,000', '$5,000-$10,000', '$10,000+'],
      },
      {
        name: 'priority',
        label: 'Priority Level',
        type: 'text',
        required: false,
        defaultHidden: true,
      },
      {
        name: 'message',
        label: 'Message',
        type: 'textarea',
        required: false,
        placeholder: 'Tell us more about your needs...',
      },
    ],
  },
]

export function getTemplateById(id: string): FormTemplate | undefined {
  return formTemplates.find(template => template.id === id)
}

export function getTemplatesByCategory(category: string): FormTemplate[] {
  return formTemplates.filter(template => template.category === category)
}

export const templateCategories = [
  'All',
  'General',
  'Marketing',
  'Support',
  'HR',
  'Events',
  'Research',
  'Sales',
  'Education',
  'Business',
  'Non-profit',
  'Hospitality',
  'Real Estate',
  'Healthcare',
  'Health & Fitness',
]
